(load "global-env.scm")

(load "analyze-procedure.scm")
(load "and.scm")
(load "application.scm")
(load "assignment.scm")
(load "begin.scm")
(load "cond.scm")
(load "defined.scm")
(load "definition.scm")
(load "eval-procedure.scm")
(load "file-to-code.scm")
(load "if.scm")
(load "lambda.scm")
(load "let-rec.scm")
(load "let.scm")
(load "let-star.scm")
(load "named-let.scm")
(load "not.scm")
(load "or.scm")
(load "quote.scm")
(load "self-evaluating.scm")
(load "thunk.scm")
(load "dorun.scm")
(load "tagged-list.scm")
(load "unspecified.scm")
(load "variable.scm")



