(define x 5)
(define y 6)
(define z (+ x y))
; this is a comment
;(display "z = ")
;(display z)
;(newline)
(load "make.scm")
(load "and.scm")
(load "assignment.scm")
(load "begin.scm")
(load "compound.scm")
(load "operands.scm")
(load "cond.scm")
(load "definition.scm")
(load "hash.scm")
(load "link-node.scm")
(load "exp-type.scm")
(load "true-false.scm")
(load "if.scm")
(load "lambda.scm")
(load "let.scm")
(load "let-star.scm")
(load "named-let.scm")
(load "not.scm")
(load "or.scm")
(load "quote.scm")
(load "variable.scm")
