(define x 5)
(define y 6)
(define z (+ x y))
; this is a comment
;(display "z = ")
;(display z)
;(newline)
(load "analyze-procedure.scm")
(load "analyze.scm")
(load "and.scm")
(load "application.scm")
(load "apply-in-underlying-scheme.scm")
(Load "apply-primitive.scm")
(load "apply.scm")
(load "assignment.scm")
(load "begin.scm")
(load "cond.scm")
(load "defined-primitive.scm")
(load "defined.scm")
(load "definition.scm")
(load "dictionary-test.scm")
(load "dict.scm")
(load "environment1.scm")
(load "environment.scm")
(load "environment-test.scm")
(load "eval-procedure.scm")
(load "eval-primitive.scm")
(load "frame.scm")
(load "frame1.scm")
(load "frame2.scm")
(load "frame3.scm")
;(load "frame-test.scm")
(load "hash.scm")
(load "link.scm")
(load "link-node.scm")
(load "load-primitive.scm")
(load "object-string-primitive.scm")
(load "primitive.scm")
(load "primitive-procedure.scm")
(load "require-primitive.scm")
(load "tagged-list.scm")
(load "unspecified.scm")
(load "global-env.scm")
(load "eval.scm")
(load "true-false.scm")
(load "if.scm")
(load "lambda.scm")
(load "let.scm")
(load "let-star.scm")
(load "named-let.scm")
(load "let-rec.scm")
(load "not.scm")
(load "or.scm")
(load "quote.scm")
(load "self-evaluating.scm")
(load "variable.scm")



