name:                Stitch
version:             0.1.0.0
github:              "githubuser/Stitch"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Stitch#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-wl-pprint >= 0.6.7.1
- parsec         >= 3.1.14.0
- hashable       >= 1.2.7.0
- containers     >= 0.5
- mtl            >= 2.2.1
- transformers   >= 0.4.0.0
- haskeline      >= 0.7.1.1
- deepseq        >= 1.4

library:
  source-dirs: src

executables:
  Stitch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Stitch

tests:
  Stitch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Stitch
