all: WordLength \
	Vehicle \
	VecSort \
	TupleVect \
	Tree \
	Printf \
	Polygon	\
	Overloading \
	Mutual	\
	Matter \
	Map \
	Length \
	Hello \
	Expr \
	EqNat \
	DepPairs \
	Adder

WordLength: WordLength.idr
	idris2 --quiet --check WordLength.idr

Vehicle: Vehicle.idr
	idris2 --quiet --check Vehicle.idr

VecSort: VecSort.idr
	idris2 --quiet --check VecSort.idr

TupleVect: TupleVect.idr
	idris2 --quiet --check TupleVect.idr

Tree: Tree.idr
	idris2 --quiet --check Tree.idr

Printf: Printf.idr
	idris2 --quiet --check Printf.idr

Polygon: Polygon.idr
	idris2 --quiet --check Polygon.idr

Overloading: Overloading.idr
	idris2 --quiet --check Overloading.idr

Mutual: Mutual.idr
	idris2 --quiet --check Mutual.idr

Matter: Matter.idr
	idris2 --quiet --check Matter.idr

Map: Map.idr
	idris2 --quiet --check Map.idr

Length: Length.idr
	idris2 --quiet --check Length.idr

Hello: Hello.idr
	idris2 --quiet --check Hello.idr

Expr: Expr.idr
	idris2 --quiet --check Expr.idr

EqNat: EqNat.idr
	idris2 --quiet --check EqNat.idr

DepPairs: DepPairs.idr
	idris2 --quiet --check DepPairs.idr

Adder: Adder.idr
	idris2 --quiet --check Adder.idr
