-- unicodes
-- ℕ : \bN
-- 𝔹 : \bB
-- → : \to, \r, \->
-- ∶ : \:  -- looks the same, but not the same as normal semi-colon
-- — : \em
-- —→: \em\to
-- —↠: \em\rr-
-- ∅ : \0, \emptyset
-- ∀ : \all
-- ∃ : \ex, \exists
-- λ : \Gl
-- ƛ : \Gl-
-- μ : \mu
-- ≡ : \==
-- ≢ : \==n
-- ≤ : \<=, \le
-- ∘ : \circ
-- × : \x
-- ⊎ : \uplus, \u+
-- ⊤ : \top
-- ⊥ : \bot
-- ¬ : ¬, \neg
-- ⟨ : \<
-- ⟩ : \>
-- ∎ : \qed
-- ∧ : \and, \wedge
-- ∨ : \or, \vee
-- ⊕ : \oplus
-- ⊗ : \otimes
-- ∸ : \.-
-- ≢ : \==n
-- ′ : \'
-- ″ : \'2
-- ‴ : \'3
-- ≥ : \>=, \ge
-- ≐ : \.=
-- ≟ : \?=
-- ℓ : \ell
-- ⊔ : \lub \sqcup
-- ₀ : \_0
-- ₁ : \_1
-- ₂ : \_2
-- ⊢ : \vdash
-- ⊨ : \vDash
-- ≃ : \~-, \simeq
-- ≲ : \<~
-- ⇔ : \iff, \<=>
-- ⇒ : \=>
-- η : \eta
-- Π : \Pi
-- Σ : \Sigma
-- ∈ : \in
-- ∉ : \notin, \inn
-- ∋ : \ni
-- ∌ : \nin
-- ⌞ : \cll
-- ⌟ : \clr
-- ⌜ : \cul
-- ⌝ : \cur
-- ⌊ : \lfloor
-- ⌋ : \rfloor
-- ⌈ : \lceil
-- ⌉ : \rceil
-- ⊃ : \supset, \sup
-- ⊂ : \subset, \sub
-- ⊇ : \supseteq
-- ⊆ : \subseteq
-- ᵇ : \^b
-- ʳ : \^r4
-- ᵣ : \_r
-- ˡ : \^l4
-- ₗ : \_l
-- ∷ : \::
-- · : \cdot (not the same as ascii '.')
