// SECP256K1_API becomes '__attribute__ ((visibility ("default")))'
// when SECP256K1_BUILD is defines, it is '' otherwise.
// #define SECP256K1_BUILD 

#include "../secp256k1/include/secp256k1.h"

#include <stdio.h>

/* trick to convert value of a macro into a string constant */
# define STR(EXP) "\'"STR_(EXP)"\'" 
# define STR_(EXP) #EXP /* # is preprocesssor 'stringify operator' */

#define DISPLAY_INT_MACRO(NAME) \
  printf(#NAME" is defined and equal to %d\n", NAME)

#define DISPLAY_STR_MACRO(NAME) \
  printf(#NAME" is defined and equal to %s\n", STR(NAME))

#define MACRO_NOT_DEFINED(NAME) \
  printf(#NAME" is not defined\n") 

#define MACRO_DEFINED(NAME) \
  printf(#NAME" is defined\n") 


int main() 
{

# if defined(SECP256K1_GNUC_PREREQ)
  MACRO_DEFINED(SECP256K1_GNUC_PREREQ);
  DISPLAY_INT_MACRO(SECP256K1_GNUC_PREREQ(6,1));
  DISPLAY_INT_MACRO(SECP256K1_GNUC_PREREQ(6,2));
  DISPLAY_INT_MACRO(SECP256K1_GNUC_PREREQ(6,3));
  DISPLAY_INT_MACRO(SECP256K1_GNUC_PREREQ(5,2));
  DISPLAY_INT_MACRO(SECP256K1_GNUC_PREREQ(7,2));
# else
  MACRO_NOT_DEFINED(SECP256K1_GNUC_PREREQ);
# endif

# if defined(__GNUC__)
  DISPLAY_INT_MACRO(__GNUC__);
# else
  MACRO_NOT_DEFINED(__GNUC__);
# endif
 
# if defined(__GNUC_MINOR__)
  DISPLAY_INT_MACRO(__GNUC_MINOR__);
# else
  MACRO_NOT_DEFINED(__GNUC_MINOR__);
# endif 

# if defined(__STDC_VERSION__)
  DISPLAY_INT_MACRO(__STDC_VERSION__);
# else
  MACRO_NOT_DEFINED(__STDC_VERSION__);
# endif

# if defined(SECP256K1_INLINE)
  DISPLAY_STR_MACRO(SECP256K1_INLINE);
# else
  MACRO_NOT_DEFINED(SECP256K1_INLINE);
# endif

# if defined(_WIN32)
  DISPLAY_STR_MACRO(_WIN32);
# else
  MACRO_NOT_DEFINED(_WIN32);
# endif

# if defined(SECP256K1_BUILD)
  DISPLAY_STR_MACRO(SECP256K1_BUILD);
# else
  MACRO_NOT_DEFINED(SECP256K1_BUILD);
# endif

# if defined(SECP256K1_API)
  DISPLAY_STR_MACRO(SECP256K1_API);
# else
  MACRO_NOT_DEFINED(SECP256K1_API);
# endif

# if defined(SECP256K1_WARN_UNUSED_RESULT)
  DISPLAY_STR_MACRO(SECP256K1_WARN_UNUSED_RESULT);
# else
  MACRO_NOT_DEFINED(SECP256K1_WARN_UNUSED_RESULT);
# endif

# if defined(SECP256K1_ARG_NONNULL)
  MACRO_DEFINED(SECP256K1_ARG_NONNULL);
  DISPLAY_STR_MACRO(SECP256K1_ARG_NONNULL(x));
# else
  MACRO_NOT_DEFINED(SECP256K1_ARG_NONNULL);
# endif

# if defined(SECP256K1_FLAGS_TYPE_MASK)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_TYPE_MASK);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_TYPE_MASK);
# endif

# if defined(SECP256K1_FLAGS_TYPE_CONTEXT)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_TYPE_CONTEXT);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_TYPE_CONTEXT);
# endif

# if defined(SECP256K1_FLAGS_TYPE_COMPRESSION)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_TYPE_COMPRESSION);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_TYPE_COMPRESSION);
# endif

# if defined(SECP256K1_FLAGS_BIT_CONTEXT_VERIFY)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_BIT_CONTEXT_VERIFY);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_BIT_CONTEXT_VERIFY);
# endif

# if defined(SECP256K1_FLAGS_BIT_CONTEXT_SIGN)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_BIT_CONTEXT_SIGN);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_BIT_CONTEXT_SIGN);
# endif

# if defined(SECP256K1_FLAGS_BIT_COMPRESSION)
  DISPLAY_INT_MACRO(SECP256K1_FLAGS_BIT_COMPRESSION);
# else
  MACRO_NOT_DEFINED(SECP256K1_FLAGS_BIT_COMPRESSION);
# endif


# if defined(SECP256K1_CONTEXT_VERIFY)
  DISPLAY_INT_MACRO(SECP256K1_CONTEXT_VERIFY);
# else
  MACRO_NOT_DEFINED(SECP256K1_CONTEXT_VERIFY);
# endif

# if defined(SECP256K1_CONTEXT_SIGN)
  DISPLAY_INT_MACRO(SECP256K1_CONTEXT_SIGN);
# else
  MACRO_NOT_DEFINED(SECP256K1_CONTEXT_SIGN);
# endif

# if defined(SECP256K1_CONTEXT_NONE)
  DISPLAY_INT_MACRO(SECP256K1_CONTEXT_NONE);
# else
  MACRO_NOT_DEFINED(SECP256K1_CONTEXT_NONE);
# endif

# if defined(SECP256K1_EC_COMPRESSED)
  DISPLAY_INT_MACRO(SECP256K1_EC_COMPRESSED);
# else
  MACRO_NOT_DEFINED(SECP256K1_EC_COMPRESSED);
# endif

# if defined(SECP256K1_EC_UNCOMPRESSED)
  DISPLAY_INT_MACRO(SECP256K1_EC_UNCOMPRESSED);
# else
  MACRO_NOT_DEFINED(SECP256K1_EC_UNCOMPRESSED);
# endif

  return 0;
}



